// Code generated by protoc-gen-go.
// DO NOT EDIT!

package appengine

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ServersServiceError_ErrorCode int32

const (
	ServersServiceError_OK                ServersServiceError_ErrorCode = 0
	ServersServiceError_INVALID_SERVER    ServersServiceError_ErrorCode = 1
	ServersServiceError_INVALID_VERSION   ServersServiceError_ErrorCode = 2
	ServersServiceError_INVALID_INSTANCES ServersServiceError_ErrorCode = 3
	ServersServiceError_TRANSIENT_ERROR   ServersServiceError_ErrorCode = 4
	ServersServiceError_UNEXPECTED_STATE  ServersServiceError_ErrorCode = 5
)

var ServersServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "INVALID_SERVER",
	2: "INVALID_VERSION",
	3: "INVALID_INSTANCES",
	4: "TRANSIENT_ERROR",
	5: "UNEXPECTED_STATE",
}
var ServersServiceError_ErrorCode_value = map[string]int32{
	"OK":                0,
	"INVALID_SERVER":    1,
	"INVALID_VERSION":   2,
	"INVALID_INSTANCES": 3,
	"TRANSIENT_ERROR":   4,
	"UNEXPECTED_STATE":  5,
}

func (x ServersServiceError_ErrorCode) Enum() *ServersServiceError_ErrorCode {
	p := new(ServersServiceError_ErrorCode)
	*p = x
	return p
}
func (x ServersServiceError_ErrorCode) String() string {
	return proto.EnumName(ServersServiceError_ErrorCode_name, int32(x))
}
func (x ServersServiceError_ErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ServersServiceError_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServersServiceError_ErrorCode_value, data, "ServersServiceError_ErrorCode")
	if err != nil {
		return err
	}
	*x = ServersServiceError_ErrorCode(value)
	return nil
}

type ServersServiceError struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ServersServiceError) Reset()         { *m = ServersServiceError{} }
func (m *ServersServiceError) String() string { return proto.CompactTextString(m) }
func (*ServersServiceError) ProtoMessage()    {}

type GetServersRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetServersRequest) Reset()         { *m = GetServersRequest{} }
func (m *GetServersRequest) String() string { return proto.CompactTextString(m) }
func (*GetServersRequest) ProtoMessage()    {}

type GetServersResponse struct {
	Server           []string `protobuf:"bytes,1,rep,name=server" json:"server,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetServersResponse) Reset()         { *m = GetServersResponse{} }
func (m *GetServersResponse) String() string { return proto.CompactTextString(m) }
func (*GetServersResponse) ProtoMessage()    {}

func (m *GetServersResponse) GetServer() []string {
	if m != nil {
		return m.Server
	}
	return nil
}

type GetVersionsRequest struct {
	Server           *string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetVersionsRequest) Reset()         { *m = GetVersionsRequest{} }
func (m *GetVersionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetVersionsRequest) ProtoMessage()    {}

func (m *GetVersionsRequest) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

type GetVersionsResponse struct {
	Version          []string `protobuf:"bytes,1,rep,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetVersionsResponse) Reset()         { *m = GetVersionsResponse{} }
func (m *GetVersionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetVersionsResponse) ProtoMessage()    {}

func (m *GetVersionsResponse) GetVersion() []string {
	if m != nil {
		return m.Version
	}
	return nil
}

type GetDefaultVersionRequest struct {
	Server           *string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetDefaultVersionRequest) Reset()         { *m = GetDefaultVersionRequest{} }
func (m *GetDefaultVersionRequest) String() string { return proto.CompactTextString(m) }
func (*GetDefaultVersionRequest) ProtoMessage()    {}

func (m *GetDefaultVersionRequest) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

type GetDefaultVersionResponse struct {
	Version          *string `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetDefaultVersionResponse) Reset()         { *m = GetDefaultVersionResponse{} }
func (m *GetDefaultVersionResponse) String() string { return proto.CompactTextString(m) }
func (*GetDefaultVersionResponse) ProtoMessage()    {}

func (m *GetDefaultVersionResponse) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type GetNumInstancesRequest struct {
	Server           *string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	Version          *string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetNumInstancesRequest) Reset()         { *m = GetNumInstancesRequest{} }
func (m *GetNumInstancesRequest) String() string { return proto.CompactTextString(m) }
func (*GetNumInstancesRequest) ProtoMessage()    {}

func (m *GetNumInstancesRequest) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *GetNumInstancesRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type GetNumInstancesResponse struct {
	Instances        *int64 `protobuf:"varint,1,req,name=instances" json:"instances,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetNumInstancesResponse) Reset()         { *m = GetNumInstancesResponse{} }
func (m *GetNumInstancesResponse) String() string { return proto.CompactTextString(m) }
func (*GetNumInstancesResponse) ProtoMessage()    {}

func (m *GetNumInstancesResponse) GetInstances() int64 {
	if m != nil && m.Instances != nil {
		return *m.Instances
	}
	return 0
}

type SetNumInstancesRequest struct {
	Server           *string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	Version          *string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Instances        *int64  `protobuf:"varint,3,req,name=instances" json:"instances,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SetNumInstancesRequest) Reset()         { *m = SetNumInstancesRequest{} }
func (m *SetNumInstancesRequest) String() string { return proto.CompactTextString(m) }
func (*SetNumInstancesRequest) ProtoMessage()    {}

func (m *SetNumInstancesRequest) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *SetNumInstancesRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *SetNumInstancesRequest) GetInstances() int64 {
	if m != nil && m.Instances != nil {
		return *m.Instances
	}
	return 0
}

type SetNumInstancesResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetNumInstancesResponse) Reset()         { *m = SetNumInstancesResponse{} }
func (m *SetNumInstancesResponse) String() string { return proto.CompactTextString(m) }
func (*SetNumInstancesResponse) ProtoMessage()    {}

type StartServerRequest struct {
	Server           *string `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	Version          *string `protobuf:"bytes,2,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StartServerRequest) Reset()         { *m = StartServerRequest{} }
func (m *StartServerRequest) String() string { return proto.CompactTextString(m) }
func (*StartServerRequest) ProtoMessage()    {}

func (m *StartServerRequest) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *StartServerRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type StartServerResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StartServerResponse) Reset()         { *m = StartServerResponse{} }
func (m *StartServerResponse) String() string { return proto.CompactTextString(m) }
func (*StartServerResponse) ProtoMessage()    {}

type StopServerRequest struct {
	Server           *string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	Version          *string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StopServerRequest) Reset()         { *m = StopServerRequest{} }
func (m *StopServerRequest) String() string { return proto.CompactTextString(m) }
func (*StopServerRequest) ProtoMessage()    {}

func (m *StopServerRequest) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *StopServerRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

type StopServerResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StopServerResponse) Reset()         { *m = StopServerResponse{} }
func (m *StopServerResponse) String() string { return proto.CompactTextString(m) }
func (*StopServerResponse) ProtoMessage()    {}

type GetHostnameRequest struct {
	Server           *string `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	Version          *string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Instance         *string `protobuf:"bytes,3,opt,name=instance" json:"instance,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetHostnameRequest) Reset()         { *m = GetHostnameRequest{} }
func (m *GetHostnameRequest) String() string { return proto.CompactTextString(m) }
func (*GetHostnameRequest) ProtoMessage()    {}

func (m *GetHostnameRequest) GetServer() string {
	if m != nil && m.Server != nil {
		return *m.Server
	}
	return ""
}

func (m *GetHostnameRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *GetHostnameRequest) GetInstance() string {
	if m != nil && m.Instance != nil {
		return *m.Instance
	}
	return ""
}

type GetHostnameResponse struct {
	Hostname         *string `protobuf:"bytes,1,req,name=hostname" json:"hostname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetHostnameResponse) Reset()         { *m = GetHostnameResponse{} }
func (m *GetHostnameResponse) String() string { return proto.CompactTextString(m) }
func (*GetHostnameResponse) ProtoMessage()    {}

func (m *GetHostnameResponse) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func init() {
	proto.RegisterEnum("appengine.ServersServiceError_ErrorCode", ServersServiceError_ErrorCode_name, ServersServiceError_ErrorCode_value)
}
